export const POST_USER = "POST_USER";
export const USER_CREATED = "USER_CREATED";
export const LOGIN_USER = "LOGIN_USER";
export const USER_CONNECTED = "USER_CONNECTED";
export const USER_CONNECTED_COMPLETED = "USER_CONNECTED_COMPLETED";
